apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sysdig-image-scanner.name" . }}-auth-watcher
  namespace: kube-system
  labels:
    {{ include "sysdig-image-scanner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sysdig-image-scanner.name" . }}-auth-watcher
subjects:
- kind: ServiceAccount
  name: {{ include "sysdig-image-scanner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
